# ==========================================================
# APLICACION
# ==========================================================

spring.application.name=clinicaMedica

# ==========================================================
# POSTGRESQL
# ==========================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/clinica_medica
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================================
# JPA / HIBERNATE
# ==========================================================

# La estructura de la BD ya fue creada manualmente.
# Hibernate solamente validara que nuestras entidades coincidan.
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Evita mantener la sesion de Hibernate abierta hasta la vista.
# La logica de datos debe resolverse en la capa Service.
spring.jpa.open-in-view=false

# ==========================================================
# THYMELEAF
# ==========================================================

spring.thymeleaf.cache=false

spring.thymeleaf.encoding=UTF-8
# ==========================================================
# SEGURIDAD - DATOS SENSIBLES
# ==========================================================

app.security.hmac-secret=${HMAC_SECRET}
app.security.aes-secret=${AES_SECRET}


# ==========================================================
# DATOS DE PRUEBA LOCAL
# ==========================================================

app.test.paciente-password=${TEST_PACIENTE_PASSWORD}
app.test.medico-password=${TEST_MEDICO_PASSWORD}
app.test.admin-password=${TEST_ADMIN_PASSWORD}
# ==========================================================
# JWT
# ==========================================================

app.security.jwt-secret=${JWT_SECRET}
app.security.jwt-expiration-minutes=30

# ==========================================================
# COOKIE JWT
# ==========================================================

app.security.jwt-cookie-name=CLINICA_AUTH

# Localhost usa HTTP.
# En producción/Azure con HTTPS se cambiará a true.
app.security.cookie-secure=false

# =========================================================
# CORREO ELECTRÓNICO - SMTP
# =========================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Evita que una falla SMTP bloquee indefinidamente un hilo
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


# =========================================================
# DATOS DEL HOSPITAL
# =========================================================

hospital.nombre=Clinica Medica
hospital.telefono=XXXXXXXX


# =========================================================
# REINTENTO DE CORREOS
# =========================================================

correo.reintento.intervalo-ms=60000

# ==========================================================
# SERVIDOR
# ==========================================================

server.port=8080