# ==========================================================
# APLICACION
# ==========================================================

spring.application.name=clinicaMedica

# ==========================================================
# POSTGRESQL
# ==========================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/clinica_medica
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================================
# JPA / HIBERNATE
# ==========================================================

# La estructura de la BD ya fue creada manualmente.
# Hibernate solamente validara que nuestras entidades coincidan.
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Evita mantener la sesion de Hibernate abierta hasta la vista.
# La logica de datos debe resolverse en la capa Service.
spring.jpa.open-in-view=false

# ==========================================================
# THYMELEAF
# ==========================================================

spring.thymeleaf.cache=false

spring.thymeleaf.encoding=UTF-8
# ==========================================================
# SEGURIDAD - DATOS SENSIBLES
# ==========================================================

app.security.hmac-secret=${HMAC_SECRET}
app.security.aes-secret=${AES_SECRET}

# ==========================================================
# DATOS DE PRUEBA LOCAL
# ==========================================================

app.test.paciente-password=${TEST_PACIENTE_PASSWORD}
app.test.medico-password=${TEST_MEDICO_PASSWORD}

# ==========================================================
# JWT
# ==========================================================

app.security.jwt-secret=${JWT_SECRET}
app.security.jwt-expiration-minutes=30

# ==========================================================
# COOKIE JWT
# ==========================================================

app.security.jwt-cookie-name=CLINICA_AUTH

# Localhost usa HTTP.
# En producción/Azure con HTTPS se cambiará a true.
app.security.cookie-secure=false

# ==========================================================
# SERVIDOR
# ==========================================================

server.port=8080