# ==========================================================
# PERFIL AZURE
# ==========================================================

spring.datasource.url=jdbc:postgresql://progra2bd.postgres.database.azure.com:5432/clinica_medica?sslmode=verify-full

spring.datasource.username=${AZURE_DB_USERNAME}
spring.datasource.password=${AZURE_DB_PASSWORD}


# ==========================================================
# PRODUCCION
# ==========================================================

spring.jpa.show-sql=false

spring.thymeleaf.cache=true

# Azure trabaja mediante HTTPS
app.security.cookie-secure=true


# ==========================================================
# CLAMAV AZURE
# ==========================================================

antivirus.clamav.host=${CLAMAV_HOST:127.0.0.1}


# ==========================================================
# DOCUMENTOS
# ==========================================================

cita.documentos.directorio=${CITA_DOCUMENTOS_DIRECTORIO:uploads/citas}