# ==========================================================
# PERFIL LOCAL
# ==========================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/clinica_medica
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}


# ==========================================================
# DESARROLLO
# ==========================================================

spring.jpa.show-sql=true

spring.thymeleaf.cache=false

app.security.cookie-secure=false


# ==========================================================
# DATOS DE PRUEBA LOCAL
# ==========================================================

app.test.paciente-password=${TEST_PACIENTE_PASSWORD}
app.test.medico-password=${TEST_MEDICO_PASSWORD}
app.test.admin-password=${TEST_ADMIN_PASSWORD}


# ==========================================================
# CLAMAV LOCAL
# ==========================================================

antivirus.clamav.host=127.0.0.1


# ==========================================================
# ARCHIVOS LOCALES
# ==========================================================

cita.documentos.directorio=uploads/citas